INSERT INTO customer_order_lines (
    cono, divi, orno, ponr, posx,
    itno, itds, teds, repi, orty,
    orst, ltyp,
    faci, whlo, whsl, bano, camu,
    orqt, rnqt, alqt, plqt, dlqt, ivqt, rtqt,
    orqa, rnqa, alqa, plqa, dlqa, ivqa, rtqa,
    alun, cofa, dmcf, spun, pcof, dccd, dcca, dccs, cofs, dmcs,
    dwdt, dwhm, codt, cohm, pldt, plhm, fded, lded,
    dwdz, dwhz, codz, cohz, tizo, dlts,
    sapr, nepr, lnam, lna2, cucd, sacd, prmo,
    ucos, cocd, uccd, inpr, cuct, edfp, prpr, ccsa,
    dip1, dip2, dip3, dip4, dip5, dip6, dip7, dip8,
    dia1, dia2, dia3, dia4, dia5, dia6, dia7, dia8,
    dic1, dic2, dic3, dic4, dic5, dic6, dic7, dic8,
    cmp1, cmp2, cmp3, cmp4, cmp5, cmp6, cmp7, cmp8,
    dibe, dire, dcha, dpst, ddsu, idsc, otdi,
    rorc, rorn, rorl, rorx,
    cuno, cuor, cupo, cusx, decu,
    atv1, atv2, atv3, atv4, atv5, atv6, atv7, atv8, atv9, atv0,
    uca1, uca2, uca3, uca4, uca5, uca6, uca7, uca8, uca9, uca0,
    udn1, udn2, udn3, udn4, udn5, udn6,
    uid1, uid2, uid3,
    uct1,
    atnr, atmo, atpr, cfin,
    proj, elno,
    cmno, smcd, bncd, prac, prrf,
    agno, bagc, bagd, agln, agnb, ctno, ctns,
    adid, rout, rodn, dsdt, dshm, modl, tedl, tel2, jdcd, dlsp, dels, splc, dlbu, spos,
    tepa, pact, cupa, d1qt,
    suno, pupr, pucd, ppun, buye, fwhl, odi1, odi2, odi3,
    prno, hdpr, moye, popn, alwt, alwq,
    vrcd, eclc, orco, vtcd, cpre, hafe, cawe, tecn,
    srcd, defc, abno, bpat, bpst, noaa, schn,
    acrf, stcd, prch, cina, ntcd, smcc,
    prtx, potx, dtid, dstx,
    e0pa, dsgp, pusn, putp, qtql,
    pide, pcla, sclb, ragn, clat, inip, mpid,
    ofno, vers, ofnr, ofsx,
    watp, gwtp, prhw, serw, pwnr, pwsx, ewst, watq,
    sern, prhl, repn,
    cnqt, dinr, disx, lncl, prio, muft, rscd, aety, scmo, mnin, apba, cfgl,
    inap, pcnr, pcsu, reli, bop1, cbsm, upav, qtbc, tomu, enno, olsc, migi,
    pikd, dpol, rsc1, rsc5, rsc6, rsc7, rsc8, arst, pmor, mprd, rasn, prhc,
    rgdt, rgtm, lmdt, chno, chid, lmts,
    m3_timestamp,
    sync_timestamp
) VALUES (...)
