apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-quota
  namespace: lp-production-planning-issues-workbench
  labels:
    app_name: "production-planning-issues-workbench"
    group: "ERP-MIS"
    app.kubernetes.io/managed-by: ping-launchpad
spec:
  hard:
    requests.cpu: "2"
    limits.cpu: "4"
    requests.memory: "4Gi"
    limits.memory: "8Gi"
    count/pods: "20"
    count/services: "5"
    count/persistentvolumeclaims: "3"
    count/secrets: "20"
    count/configmaps: "20"
