apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-rinit-b
  namespace: lp-production-planning-issues-workbench
  labels:
    group: "ERP-MIS"
    app_name: "postgres"
    contact_person: "douglasl_at_ping_com"
    pvc-config-hash: "rinit-b"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-nfs-premium  # Azure Files NFS — platform standard for PostgreSQL
  resources:
    requests:
      storage: 10Gi
